Alias /.well-known/acme-challenge/ /var/www/letsencrypt/.well-known/acme-challenge/

<Directory "/var/www/letsencrypt/.well-known/acme-challenge/">
    Options None
    AllowOverride None
    Require all granted
</Directory>

<Directory "/var/www/html">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

<VirtualHost *:80>
    ServerName vps-prd.pyrosa.com.do

    ProxyPass /.well-known/acme-challenge/ !
    RewriteEngine On
    RewriteRule ^/(.*)$ https://vps-prd.pyrosa.com.do/$1 [R=302,L]

    ErrorLog /var/log/httpd/vps-prd.pyrosa.com.do_error.log
    CustomLog /var/log/httpd/vps-prd.pyrosa.com.do_access.log combined
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName vps-prd.pyrosa.com.do
    DocumentRoot "/var/www/html"
    DirectoryIndex index.html

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/vps-prd.pyrosa.com.do/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/vps-prd.pyrosa.com.do/privkey.pem

    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"

    ErrorLog /var/log/httpd/vps-prd.pyrosa.com.do_ssl_error.log
    CustomLog /var/log/httpd/vps-prd.pyrosa.com.do_ssl_access.log combined
</VirtualHost>

<VirtualHost 51.222.204.86:3200>
    ServerName vps-prd.pyrosa.com.do

    AllowEncodedSlashes NoDecode

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/vps-prd.pyrosa.com.do/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/vps-prd.pyrosa.com.do/privkey.pem

    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyAddHeaders On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "3200"

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule /(.*) ws://127.0.0.1:10170/$1 [P,L]

    ProxyPass / http://127.0.0.1:10170/ nocanon retry=0 timeout=120
    ProxyPassReverse / http://127.0.0.1:10170/

    ErrorLog /var/log/httpd/vps-prd.pyrosa.com.do_3200_ssl_error.log
    CustomLog /var/log/httpd/vps-prd.pyrosa.com.do_3200_ssl_access.log combined
</VirtualHost>

</IfModule>
