import { type WebLocale } from "./request.js";
import { type LocalizedMailCopy } from "./mail-section-types.js";

export function getMailSectionCopy(locale: WebLocale): LocalizedMailCopy {
  return locale === "es"
    ? {
        title: "Mail",
        description:
          "Dominios de correo, buzones, aliases y quotas definidos en SimpleHost Control para el stack mail de la plataforma.",
        domainsTitle: "Dominios mail",
        mailboxesTitle: "Buzones",
        aliasesTitle: "Aliases",
        quotasTitle: "Quotas",
        formsTitle: "Edición operativa",
        formsDescription:
          "Gestiona buzones con credenciales generadas, manuales o en reset requerido. La recuperación sigue siendo solo por reset, nunca por lectura.",
        modalEditorDescription:
          "Abre un editor modal para crear un registro nuevo o ajustar el seleccionado.",
        modalDeleteDescription:
          "Confirma la eliminación del registro seleccionado antes de aplicar el cambio.",
        selectedDomainTitle: "Dominio seleccionado",
        selectedMailboxTitle: "Buzón seleccionado",
        selectedAliasTitle: "Alias seleccionado",
        selectedQuotaTitle: "Quota seleccionada",
        createLabel: "Crear",
        editLabel: "Editar",
        rotateLabel: "Rotar",
        resetLabel: "Resetear",
        deleteLabel: "Eliminar",
        actionsLabel: "Acciones",
        openEditorLabel: "Crear o editar",
        deleteSelectedLabel: "Eliminar seleccionado",
        selectedRecordLabel: "Seleccionado",
        noSelectionLabel: "Selecciona un registro primero",
        closeLabel: "Cerrar",
        domainNameLabel: "Dominio",
        mailHostLabel: "Mail host",
        webmailHostnameLabel: "Webmail host",
        dkimSelectorLabel: "Selector DKIM",
        quotaBytesLabel: "Quota",
        hasCredentialLabel: "Credencial",
        destinationsLabel: "Destinos",
        mailboxCountLabel: "Buzones",
        aliasCountLabel: "Aliases",
        runtimeTitle: "Runtime por nodo",
        runtimeDescription:
          "Estado reportado por SimpleHost Agent para postfix, dovecot, rspamd, redis y los dominios gestionados por nodo.",
        runtimeNodesLabel: "Nodos runtime",
        runtimeHealthyLabel: "Nodos sanos",
        postfixLabel: "Postfix",
        dovecotLabel: "Dovecot",
        rspamdLabel: "Rspamd",
        redisLabel: "Redis",
        managedDomainsLabel: "Dominios gestionados",
        checkedAtLabel: "Verificado",
        primaryRoleLabel: "Primario",
        secondaryRoleLabel: "Secundario",
        primaryNodeLabel: "Nodo primario",
        standbyNodeLabel: "Nodo secundario",
        saveDomainLabel: "Guardar dominio",
        deleteDomainLabel: "Eliminar dominio",
        saveMailboxLabel: "Guardar buzón",
        resetMailboxCredentialLabel: "Resetear credencial",
        deleteMailboxLabel: "Eliminar buzón",
        saveAliasLabel: "Guardar alias",
        deleteAliasLabel: "Eliminar alias",
        saveQuotaLabel: "Guardar quota",
        deleteQuotaLabel: "Eliminar quota",
        desiredPasswordLabel: "Contraseña manual",
        credentialStrategyLabel: "Estrategia de credencial",
        credentialStrategyGenerateLabel: "Generar temporal",
        credentialStrategyManualLabel: "Establecer manualmente",
        credentialStrategyMissingLabel: "Dejar faltante",
        credentialStrategyKeepLabel: "Conservar actual",
        createMailboxDescription:
          "Crea el buzón con una contraseña temporal generada, una manual o dejándolo en estado faltante.",
        editMailboxDescription:
          "Edita el buzón sin tocar la credencial, establece una manual nueva o déjalo en reset requerido.",
        manualPasswordHelp:
          "Las credenciales generadas se muestran una sola vez. Si eliges manual, debes escribirla ahora.",
        localPartLabel: "Local part",
        addressLabel: "Dirección",
        tenantSlugLabel: "Tenant",
        zoneNameLabel: "Zona",
        domainCountLabel: "Dominios",
        mailboxTotalLabel: "Buzones",
        aliasTotalLabel: "Aliases",
        quotaTotalLabel: "Quotas",
        credentialConfigured: "configurada",
        credentialMissing: "faltante",
        credentialResetRequired: "reset requerido",
        credentialRevealTitle: "Credencial de buzón",
        credentialRevealDescription:
          "Guarda esta contraseña ahora. SimpleHostMan solo la mostrará una vez.",
        credentialRevealValueLabel: "Contraseña temporal",
        credentialRevealShownOnce: "Visible solo una vez",
        credentialRevealMailboxLabel: "Buzón",
        credentialRevealGeneratedLabel: "Generada",
        credentialRevealRotatedLabel: "Rotada",
        runtimeReported: "reportado",
        runtimeUnreported: "sin reporte",
        serviceActive: "active",
        serviceInactive: "inactive",
        serviceDisabled: "disabled",
        noMailDomains: "No hay dominios mail.",
        noMailboxes: "No hay buzones.",
        noAliases: "No hay aliases.",
        noQuotas: "No hay quotas.",
        noRuntimeNodes: "Ningún nodo relevante ha reportado runtime mail todavía."
      }
    : {
        title: "Mail",
        description:
          "Mail domains, mailboxes, aliases and quotas defined in SimpleHost Control for the platform mail stack.",
        domainsTitle: "Mail domains",
        mailboxesTitle: "Mailboxes",
        aliasesTitle: "Aliases",
        quotasTitle: "Quotas",
        formsTitle: "Operator editing",
        formsDescription:
          "Manage mailboxes with generated, manual, or reset-required credentials. Recovery remains reset-only and never readable.",
        modalEditorDescription:
          "Open a modal editor to create a new record or adjust the selected one.",
        modalDeleteDescription:
          "Confirm the selected record before applying a destructive delete.",
        selectedDomainTitle: "Selected domain",
        selectedMailboxTitle: "Selected mailbox",
        selectedAliasTitle: "Selected alias",
        selectedQuotaTitle: "Selected quota",
        createLabel: "Create",
        editLabel: "Edit",
        rotateLabel: "Rotate",
        resetLabel: "Reset",
        deleteLabel: "Delete",
        actionsLabel: "Actions",
        openEditorLabel: "Create or edit",
        deleteSelectedLabel: "Delete selected",
        selectedRecordLabel: "Selected",
        noSelectionLabel: "Select a record first",
        closeLabel: "Close",
        domainNameLabel: "Domain",
        mailHostLabel: "Mail host",
        webmailHostnameLabel: "Webmail host",
        dkimSelectorLabel: "DKIM selector",
        quotaBytesLabel: "Quota",
        hasCredentialLabel: "Credential",
        destinationsLabel: "Destinations",
        mailboxCountLabel: "Mailboxes",
        aliasCountLabel: "Aliases",
        runtimeTitle: "Node runtime",
        runtimeDescription:
          "Per-node mail service status reported by SimpleHost Agent for postfix, dovecot, rspamd, redis and managed domains.",
        runtimeNodesLabel: "Runtime nodes",
        runtimeHealthyLabel: "Healthy nodes",
        postfixLabel: "Postfix",
        dovecotLabel: "Dovecot",
        rspamdLabel: "Rspamd",
        redisLabel: "Redis",
        managedDomainsLabel: "Managed domains",
        checkedAtLabel: "Checked",
        primaryRoleLabel: "Primary",
        secondaryRoleLabel: "Secondary",
        primaryNodeLabel: "Primary node",
        standbyNodeLabel: "Standby node",
        saveDomainLabel: "Save domain",
        deleteDomainLabel: "Delete domain",
        saveMailboxLabel: "Save mailbox",
        resetMailboxCredentialLabel: "Reset credential",
        deleteMailboxLabel: "Delete mailbox",
        saveAliasLabel: "Save alias",
        deleteAliasLabel: "Delete alias",
        saveQuotaLabel: "Save quota",
        deleteQuotaLabel: "Delete quota",
        desiredPasswordLabel: "Manual password",
        credentialStrategyLabel: "Credential strategy",
        credentialStrategyGenerateLabel: "Generate temporary",
        credentialStrategyManualLabel: "Set manually",
        credentialStrategyMissingLabel: "Leave missing",
        credentialStrategyKeepLabel: "Keep current",
        createMailboxDescription:
          "Create the mailbox with a generated temporary password, a manual password, or leave it missing.",
        editMailboxDescription:
          "Edit the mailbox without changing the credential, set a new manual one, or move it to reset-required.",
        manualPasswordHelp:
          "Generated credentials are shown only once. If you choose manual, enter the password now.",
        localPartLabel: "Local part",
        addressLabel: "Address",
        tenantSlugLabel: "Tenant",
        zoneNameLabel: "Zone",
        domainCountLabel: "Domains",
        mailboxTotalLabel: "Mailboxes",
        aliasTotalLabel: "Aliases",
        quotaTotalLabel: "Quotas",
        credentialConfigured: "configured",
        credentialMissing: "missing",
        credentialResetRequired: "reset required",
        credentialRevealTitle: "Mailbox credential",
        credentialRevealDescription:
          "Save this password now. SimpleHostMan will only show it once.",
        credentialRevealValueLabel: "Temporary password",
        credentialRevealShownOnce: "Shown only once",
        credentialRevealMailboxLabel: "Mailbox",
        credentialRevealGeneratedLabel: "Generated",
        credentialRevealRotatedLabel: "Rotated",
        runtimeReported: "reported",
        runtimeUnreported: "unreported",
        serviceActive: "active",
        serviceInactive: "inactive",
        serviceDisabled: "disabled",
        noMailDomains: "No mail domains.",
        noMailboxes: "No mailboxes.",
        noAliases: "No aliases.",
        noQuotas: "No quotas.",
        noRuntimeNodes: "No relevant nodes have reported mail runtime yet."
      };
}
