import { type WebLocale } from "./request.js";
import { type WebCopyDictionary } from "./web-copy-types.js";

export const resourcesCopyByLocale = {
  en: {
    desiredStateTitle: "Resources",
    desiredStateDescription:
      "Create and operate platform resources through object-specific workspaces.",
    desiredStateInventoryTitle: "Resource inventory",
    desiredStateInventoryDescription:
      "Review the current platform catalog before editing an individual record.",
    desiredStateEditorsTitle: "Resource configuration",
    desiredStateEditorsDescription:
      "Apply changes through these forms. Each save updates the PostgreSQL resource catalog.",
    selectedResourceTitle: "Selected resource",
    selectedResourceDescription:
      "Use the inventory table to change focus and run actions against a single resource.",
    propertiesStatusTitle: "Properties and status",
    propertiesStatusDescription:
      "Core properties, linked resources and current control-plane status for the selected record.",
    resourceActionsTitle: "Actions",
    resourceActionsDescription:
      "Open related operational views or dispatch work for the selected record.",
    proxyPropertiesTitle: "Properties and status",
    proxyPropertiesDescription:
      "Core proxy properties, target nodes and current runtime status for the selected record.",
    proxyDatabaseTitle: "Database",
    proxyDatabaseDescription:
      "Linked database resource currently backing the selected app.",
    proxyActionsTitle: "Actions",
    proxyActionsDescription:
      "Open related operational views or dispatch proxy work for the selected record.",
    openZoneRecordsModal: "View / edit DNS records",
    zoneRecordsModalTitle: "DNS records",
    zoneRecordsModalDescription:
      "Review and update the raw DNS record set for the selected zone.",
    zoneRecordsModalFormatHint:
      "Use one line per record: <name> <type> <value> <ttl>.",
    saveZoneRecords: "Save DNS records",
    selectedStateLabel: "Selected",
    detailActionsTitle: "Context actions",
    recordPreviewTitle: "Record preview",
    appRuntimeTitle: "Runtime and routing",
    databaseAccessTitle: "Topology and access",
    dataFilterPlaceholder: "Filter records",
    rowsPerPage: "Rows per page",
    showing: "Showing",
    of: "of",
    records: "records",
    tenantColSlug: "Slug",
    tenantColDisplayName: "Display name",
    nodeColNode: "Node",
    nodeColHostname: "Hostname",
    nodeSpecColPublicIpv4: "Public IPv4",
    nodeSpecColWireguard: "WireGuard",
    nodeColVersion: "Version",
    nodeColPending: "Pending",
    nodeColLatestStatus: "Latest status",
    nodeColLatestSummary: "Latest summary",
    nodeColLastSeen: "Last seen",
    zoneColZone: "Zone",
    zoneColTenant: "Tenant",
    zoneColPrimaryNode: "Primary node",
    zoneColRecordCount: "Records",
    appColSlug: "App",
    appColTenant: "Tenant",
    appColDomain: "Domain",
    appColMode: "Mode",
    modeHealthLabel: "Mode / Health",
    appColNodes: "Nodes",
    recordColName: "Name",
    recordColType: "Type",
    recordColValue: "Value",
    recordColTtl: "TTL",
    aliasesLabel: "Aliases",
    backendPortLabel: "Backend port",
    runtimeImageLabel: "Runtime image",
    storageRootLabel: "Storage root",
    databaseColApp: "App",
    databaseColEngine: "Engine",
    databaseColDatabase: "Database",
    databaseColUser: "User",
    databaseColNodes: "Nodes",
    databaseColMigration: "Migration",
    migrationPendingLabel: "Pending",
    migrationCompletedLabel: "Completed",
    migrationCompletedAtLabel: "Completed at",
    backupPolicyColSlug: "Policy",
    backupPolicyColTenant: "Tenant",
    backupPolicyColTargetNode: "Target node",
    backupPolicyColSchedule: "Schedule",
    backupPolicyColRetention: "Retention",
    driftColKind: "Kind",
    driftColResource: "Resource",
    driftColNode: "Node",
    driftColDrift: "Drift",
    driftColLatestStatus: "Latest status",
    driftColSummary: "Summary",
    jobColJob: "Job",
    jobColKind: "Kind",
    jobColNode: "Node",
    jobColStatus: "Status",
    jobColReason: "Reason",
    jobColSummary: "Summary",
    jobColCreated: "Created",
    backupColPolicy: "Policy",
    backupColNode: "Node",
    backupColStatus: "Status",
    backupColSummary: "Summary",
    backupColStarted: "Started",
    noTenants: "No tenants.",
    noNodes: "No nodes.",
    noZones: "No zones.",
    noApps: "No apps.",
    noDatabases: "No databases.",
    noBackupPolicies: "No backup policies.",
    noDrift: "No drift records.",
    noJobs: "No jobs.",
    noBackups: "No backup runs.",
    tabCreate: "Create",
    tabSummary: "Summary",
    tabSpec: "Spec",
    tabActivity: "Activity",
    tabTenants: "Tenants",
    tabNodes: "Nodes",
    tabZones: "DNS zones",
    tabApps: "Apps",
    tabDatabases: "Databases",
    tabBackupPolicies: "Backup policies"
  },
  es: {
    desiredStateTitle: "Recursos",
    desiredStateDescription:
      "Crea y opera recursos de plataforma mediante workspaces por objeto.",
    desiredStateInventoryTitle: "Inventario de recursos",
    desiredStateInventoryDescription:
      "Revisa el catálogo actual de la plataforma antes de editar un registro individual.",
    desiredStateEditorsTitle: "Configuración del recurso",
    desiredStateEditorsDescription:
      "Aplica cambios mediante estos formularios. Cada guardado actualiza el catálogo de recursos en PostgreSQL.",
    selectedResourceTitle: "Recurso seleccionado",
    selectedResourceDescription:
      "Usa la tabla de inventario para cambiar el foco y ejecutar acciones sobre un recurso puntual.",
    propertiesStatusTitle: "Propiedades y estado",
    propertiesStatusDescription:
      "Propiedades clave, recursos vinculados y estado actual de control plane del registro seleccionado.",
    resourceActionsTitle: "Acciones",
    resourceActionsDescription:
      "Abre vistas operativas relacionadas o despacha trabajo para el registro seleccionado.",
    proxyPropertiesTitle: "Propiedades y estado",
    proxyPropertiesDescription:
      "Propiedades clave del proxy, nodos destino y estado runtime actual del registro seleccionado.",
    proxyDatabaseTitle: "Base de datos",
    proxyDatabaseDescription:
      "Recurso de base de datos vinculado que respalda actualmente la app seleccionada.",
    proxyActionsTitle: "Acciones",
    proxyActionsDescription:
      "Abre vistas operativas relacionadas o despacha trabajo de proxy para el registro seleccionado.",
    openZoneRecordsModal: "Ver / editar registros DNS",
    zoneRecordsModalTitle: "Registros DNS",
    zoneRecordsModalDescription:
      "Revisa y actualiza la definición raw de registros DNS de la zona seleccionada.",
    zoneRecordsModalFormatHint:
      "Usa una línea por registro: <nombre> <tipo> <valor> <ttl>.",
    saveZoneRecords: "Guardar registros DNS",
    selectedStateLabel: "Seleccionado",
    detailActionsTitle: "Acciones contextuales",
    recordPreviewTitle: "Vista de registros",
    appRuntimeTitle: "Runtime y enrutamiento",
    databaseAccessTitle: "Topología y acceso",
    dataFilterPlaceholder: "Filtrar registros",
    rowsPerPage: "Filas por página",
    showing: "Mostrando",
    of: "de",
    records: "registros",
    tenantColSlug: "Slug",
    tenantColDisplayName: "Nombre visible",
    nodeColNode: "Nodo",
    nodeColHostname: "Hostname",
    nodeSpecColPublicIpv4: "IPv4 pública",
    nodeSpecColWireguard: "WireGuard",
    nodeColVersion: "Versión",
    nodeColPending: "Pendientes",
    nodeColLatestStatus: "Último estado",
    nodeColLatestSummary: "Último resumen",
    nodeColLastSeen: "Última señal",
    zoneColZone: "Zona",
    zoneColTenant: "Tenant",
    zoneColPrimaryNode: "Nodo primario",
    zoneColRecordCount: "Registros",
    appColSlug: "App",
    appColTenant: "Tenant",
    appColDomain: "Dominio",
    appColMode: "Modo",
    modeHealthLabel: "Modo / salud",
    appColNodes: "Nodos",
    recordColName: "Nombre",
    recordColType: "Tipo",
    recordColValue: "Valor",
    recordColTtl: "TTL",
    aliasesLabel: "Aliases",
    backendPortLabel: "Puerto backend",
    runtimeImageLabel: "Imagen runtime",
    storageRootLabel: "Raíz de storage",
    databaseColApp: "App",
    databaseColEngine: "Motor",
    databaseColDatabase: "Base",
    databaseColUser: "Usuario",
    databaseColNodes: "Nodos",
    databaseColMigration: "Migración",
    migrationPendingLabel: "Pendiente",
    migrationCompletedLabel: "Completada",
    migrationCompletedAtLabel: "Completada el",
    backupPolicyColSlug: "Política",
    backupPolicyColTenant: "Tenant",
    backupPolicyColTargetNode: "Nodo destino",
    backupPolicyColSchedule: "Horario",
    backupPolicyColRetention: "Retención",
    driftColKind: "Tipo",
    driftColResource: "Recurso",
    driftColNode: "Nodo",
    driftColDrift: "Drift",
    driftColLatestStatus: "Último estado",
    driftColSummary: "Resumen",
    jobColJob: "Job",
    jobColKind: "Tipo",
    jobColNode: "Nodo",
    jobColStatus: "Estado",
    jobColReason: "Motivo",
    jobColSummary: "Resumen",
    jobColCreated: "Creado",
    backupColPolicy: "Política",
    backupColNode: "Nodo",
    backupColStatus: "Estado",
    backupColSummary: "Resumen",
    backupColStarted: "Inicio",
    noTenants: "No hay tenants.",
    noNodes: "No hay nodos.",
    noZones: "No hay zonas.",
    noApps: "No hay apps.",
    noDatabases: "No hay bases de datos.",
    noBackupPolicies: "No hay políticas de backup.",
    noDrift: "No hay registros de drift.",
    noJobs: "No hay jobs.",
    noBackups: "No hay ejecuciones de backup.",
    tabCreate: "Crear",
    tabSummary: "Resumen",
    tabSpec: "Especificación",
    tabActivity: "Actividad",
    tabTenants: "Tenants",
    tabNodes: "Nodos",
    tabZones: "Zonas DNS",
    tabApps: "Apps",
    tabDatabases: "Bases de datos",
    tabBackupPolicies: "Políticas de backup"
  }
} satisfies Record<WebLocale, WebCopyDictionary>;
